//! Voice-lock corpus commands: count and clear a character's `rvc_corpus/`.
//!
//! The corpus is the character's real lines, filled from a dissected
//! recording (`emotions::corpus_from_dissect`) or imported audio
//! (`character::import_audio_files_into_corpus`). It used to be generated by
//! cloning palette references with Chatterbox; that path is gone — synthetic
//! takes taught RVC the cloning engine's voice, not the character's.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use tauri::AppHandle;

use crate::app_support::app_projects_dir;
use crate::error::Result;

/// How many corpus WAVs exist for one emotion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmotionCorpusCount {
    pub emotion: String,
    pub count: usize,
}

// ── Paths ─────────────────────────────────────────────────────────────────

fn corpus_dir(projects_dir: &Path, project_id: &str, character_id: &str) -> PathBuf {
    projects_dir
        .join(project_id)
        .join("characters")
        .join(character_id)
        .join("rvc_corpus")
}

/// Corpus files are named `{emotion}_{index}.wav`, so the emotion is the part
/// before the final underscore. Names without an underscore are counted under
/// `"imported"` — bulk-imported real recordings carry their original filename.
fn emotion_of(file_stem: &str) -> String {
    match file_stem.rsplit_once('_') {
        Some((head, tail)) if !head.is_empty() && tail.chars().all(|c| c.is_ascii_digit()) => {
            head.to_string()
        }
        _ => "imported".to_string(),
    }
}

// ── Commands ──────────────────────────────────────────────────────────────

/// Count corpus WAVs per emotion, so the Corpus tab can show which emotional
/// states are under-represented.
#[tauri::command]
pub async fn get_corpus_emotion_counts(
    app: AppHandle,
    project_id: String,
    character_id: String,
) -> Result<Vec<EmotionCorpusCount>> {
    let projects_dir = app_projects_dir(&app)?;
    let dir = corpus_dir(&projects_dir, &project_id, &character_id);
    if !dir.exists() {
        return Ok(Vec::new());
    }

    let mut counts: HashMap<String, usize> = HashMap::new();
    for entry in std::fs::read_dir(&dir)?.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("wav") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        // The sidecar's emotion when it records one (lines lifted from a
        // recording are named rec_<import>_<ms>); else the filename's prefix.
        let from_meta = std::fs::read_to_string(dir.join(format!("{}.wav.meta.json", stem)))
            .ok()
            .and_then(|raw| serde_json::from_str::<serde_json::Value>(&raw).ok())
            .and_then(|m| m["emotion"].as_str().map(str::to_string))
            .filter(|e| !e.is_empty());
        *counts.entry(from_meta.unwrap_or_else(|| emotion_of(stem))).or_insert(0) += 1;
    }

    let mut out: Vec<EmotionCorpusCount> = counts
        .into_iter()
        .map(|(emotion, count)| EmotionCorpusCount { emotion, count })
        .collect();
    // Stable ordering so the UI list does not shuffle between polls.
    out.sort_by(|a, b| a.emotion.cmp(&b.emotion));
    Ok(out)
}

/// Delete every generated corpus WAV and its sidecar.
///
/// Removes the files rather than the directory so a corpus can be rebuilt
/// without recreating the tree, and leaves anything that is not a `.wav` or
/// its `.meta.json` alone.
#[tauri::command]
pub async fn clear_corpus(
    app: AppHandle,
    project_id: String,
    character_id: String,
) -> Result<usize> {
    let projects_dir = app_projects_dir(&app)?;
    let dir = corpus_dir(&projects_dir, &project_id, &character_id);
    if !dir.exists() {
        return Ok(0);
    }

    let mut removed = 0usize;
    for entry in std::fs::read_dir(&dir)?.flatten() {
        let path = entry.path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        let is_corpus_file = name.ends_with(".wav") || name.ends_with(".wav.meta.json");
        if is_corpus_file && path.is_file() {
            std::fs::remove_file(&path)?;
            removed += 1;
        }
    }
    Ok(removed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emotion_is_the_stem_before_the_take_number() {
        assert_eq!(emotion_of("neutral_000"), "neutral");
        assert_eq!(emotion_of("quiet_dread_012"), "quiet_dread");
    }

    #[test]
    fn names_without_a_numeric_suffix_count_as_imported() {
        assert_eq!(emotion_of("interview_take"), "imported");
        assert_eq!(emotion_of("recording"), "imported");
        assert_eq!(emotion_of("_007"), "imported");
    }
}
